#!/bin/bash
HELLO='Welcome to Play With Yourself, an accompaniment tool for the modern musician.'
echo $HELLO
echo " "
echo "In order to run the app, you need to have several python modules installed. If you have already installed these through this program or another, type 'pass' and press [RETURN] to launch app. Type 'install' and press [RETURN] to install all required modules. "
read cmd

cwd=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/src

if [ $cmd == "install" ]; then
	# Install homebrew
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
	brewtest=$?
	if [ $brewtest -eq 1 ]; then
	    echo FAIL
	else
	    echo 'brew install successful'
	    # Install pip
		curl -O http://python-distribute.org/distribute_setup.py
		sudo easy_install pip
		piptest=$?
		if [ $piptest -eq 1 ]; then
		    echo FAIL
		else
		    echo 'pip install successful'
		    #mv distribute_setup.py $cwd/www/
		    # Install Librosa (so to install other libraries through Librosa setup)
			sudo -H pip install --ignore-installed librosa
			librosatest=$?
			if [ $librosatest -eq 1 ]; then
			    echo FAIL
			else
			    echo 'librosa install successful'
			    # Install joblib (for librosa)
				sudo -H pip install --ignore-installed joblib
				joblibtest=$?
				if [ $joblibtest -eq 1 ]; then
				    echo FAIL
				else
					echo 'joblib install successful'
					# Install decorator (for librosa)
					sudo -H pip install --ignore-installed decorator
					decoratortest=$?
					if [ $decoratortest -eq 1 ]; then
					    echo FAIL
					else
					    echo 'decorator install successful'
					    # Install Pyaudio (requires portaudio)
						brew install portaudio
						brew link portaudio
						portaudiotest=$?
						if [ $portaudiotest -eq 1 ]; then
						    echo FAIL
						else
						    echo 'portaudio install successful'
						    sudo -H pip install --ignore-installed pyaudio
							pyaudiotest=$?
							if [ $pyaudiotest -eq 1 ]; then
							    echo FAIL
							else
							    echo 'pyaudio install successful'
							    # Install scikits.audiolab (requires libsndfile)
								brew install libsndfile
								libsndfiletest=$?
								if [ $libsndfiletest -eq 1 ]; then
								    echo FAIL
								else
								    echo 'libsndfile install successful'
								    #sudo -H pip uninstall scikits.io.wavfile
								    sudo -H pip install scikits.io.wavfile
									scikits.io.wavtest=$?
									if [ $scikits.io.wavtest -eq 1 ]; then
									    echo FAIL
									else
										echo 'scikits.io.wav install successful'
										# Install sox and fluidsynth (for mixing)
										sudo -H pip install pyaudio
										pyaudiotest=$?
										if [ $pyaudiotest -eq 1 ]; then
											echo FAIL
										else
											echo 'pyaudio install successful'
											# Install sox and fluidsynth (for mixing)
											sudo -H pip install wave
											wavetest=$?
											if [ $wavetest -eq 1 ]; then
											    echo FAIL
											else
											    echo 'wave install successful'
											    # Install sox and fluidsynth (for mixing)
												brew install sox
												soxtest=$?
												if [ $soxtest -eq 1 ]; then
												    echo FAIL
												else
												    echo 'SoX install successful'
												    brew install fluidsynth
													fluidsynthtest=$?
													if [ $fluidsynthtest -eq 1 ]; then
													    echo FAIL
													else
													    echo 'fluidsynth install successful'
													    # Install flask (server host)
														sudo -H pip install --ignore-installed flask
														flasktest=$?
														if [ $flasktest -eq 1 ]; then
														    echo FAIL
														else
														    echo 'flask install successful'
														fi
														echo 'Play With Yourself is ready to use'
													fi
												fi
											fi
										fi
									fi
								fi
							fi
						fi
					fi
				fi
			fi
		fi
	fi	
fi
echo "Ok. Launching Play With Yourself"
python $cwd/app.py




